### ISSUE TITLE
Provide runtime mechanism to apply RobolectricExtension

### ISSUE THREAD

**Issue by tadfisher** [kotest/kotest-extensions-robolectric#3]
I'm developing an extension for Jetpack Compose which should be usable from a Kotlin common target. To achieve this, I wish to enable Robolectric automatically when we detect we are running on a desktop host with Robolectric on the classpath. Since there is already a Robolectric extension for Kotest, it makes sense to use this instead of reimplementing the extension internally, and that allows for interoperability with existing tests using the Robolectric extension.

Unfortunately, the Robolectric extension implementation is internal, and can only be applied to a spec via the `@RobolectricTest` annotation. A quick-and-dirty way to solve for my use-case would be to make `RobolectricExtension` public, but there are probably safer options.

**Comment by LeoColman** [comment]
I don't see an issue with it being public.
Would you like to submit a PR for this?
